name: Scaffold PRs

on:
  [
    pull_request,
    pull_request_review_comment,
    pull_request_review,
    pull_request_target,
  ]

jobs:
  request:
    name: Request reviews on PRs
    runs-on: ubuntu-20.04
    # if: github.event.pull_request.head.repo.full_name == 'FindShelter/test_playaround'

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # - name: Add reviewers
      #   uses: shreystechtips/actions-assigner@v1.0.3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     reviewers: shreystechtips
      #     assignees: shreystechtips

      - uses: hkusu/review-assign-action@v1
        id: assign # specify id
        with:
          assignees: shreystechtips
          reviewers: shreystechtips

      - name: Label the PR
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "cool"
