name: Scaffold PRs

on: [pull_request, pull_request_target]

jobs:
  request:
    name: Request reviews on PRs
    runs-on: ubuntu-20.04
    if: github.event.pull_request.head.repo.full_name == 'FindShelter/test_playaround'

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Add Reviewers
        uses: shreystechtips/add-reviewers@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: shreystechtips

      - name: Use GH CLI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          gh pr edit "${{ github.event.pull_request._links.html.href }}" --add-reviewer shreystechtips  --add-assignee shreystechtips

      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            @shreystechtips
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label the PR
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "cool"
